-- MySQL Script generated by MySQL Workbench
-- jeu. 28 sept. 2023 16:23:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema square_game
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema square_game
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `square_game` DEFAULT CHARACTER SET utf8 ;
USE `square_game` ;

-- -----------------------------------------------------
-- Table `square_game`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `square_game`.`Users` (
                                              `id` INT NOT NULL AUTO_INCREMENT,
                                              `login` VARCHAR(45) NOT NULL,
    `password` VARCHAR(45) NOT NULL,
    `avatar` VARCHAR(45) NULL,
    `pseudo` VARCHAR(45) NULL,
    `email` VARCHAR(255) NULL,
    `birth_date` DATE NOT NULL,
    `jetons` INT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `pseudo_UNIQUE` (`pseudo` ASC) VISIBLE,
    UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
    UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `square_game`.`games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `square_game`.`Games` (
                                              `id` INT NOT NULL AUTO_INCREMENT,
                                              `name` VARCHAR(45) NOT NULL,
    `min_age` INT NULL,
    `size` INT NOT NULL,
    `difficulties` JSON NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `square_game`.`matchs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `square_game`.`Matchs` (
                                               `id` INT NOT NULL AUTO_INCREMENT,
                                               `games_id` INT NOT NULL,
                                               `date_start` DATE NULL,
                                               `status` VARCHAR(10) NULL,
    `next_player` INT NULL,
    `winner` INT NULL,
    `looser` INT NULL,
    PRIMARY KEY (`id`, `games_id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
    INDEX `fk_matchs_games_idx` (`games_id` ASC) VISIBLE,
    CONSTRAINT `fk_matchs_games`
    FOREIGN KEY (`games_id`)
    REFERENCES `square_game`.`Games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `square_game`.`users_has_matchs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `square_game`.`Users_has_matchs` (
                                                         `users_id` INT NOT NULL,
                                                         `matchs_id` INT NOT NULL,
                                                         PRIMARY KEY (`users_id`, `matchs_id`),
    INDEX `fk_users_has_matchs_matchs1_idx` (`matchs_id` ASC) VISIBLE,
    INDEX `fk_users_has_matchs_users1_idx` (`users_id` ASC) VISIBLE,
    CONSTRAINT `fk_users_has_matchs_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `square_game`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_users_has_matchs_matchs1`
    FOREIGN KEY (`matchs_id`)
    REFERENCES `square_game`.`Matchs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `square_game`.`moves`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `square_game`.`Moves` (
                                              `id` INT NOT NULL AUTO_INCREMENT,
                                              `matchs_id` INT NOT NULL,
                                              `pos_start` VARCHAR(45) NULL,
    `pos_end` VARCHAR(45) NULL,
    `date` DATE NULL,
    PRIMARY KEY (`id`, `matchs_id`),
    INDEX `fk_moves_matchs1_idx` (`matchs_id` ASC) VISIBLE,
    CONSTRAINT `fk_moves_matchs1`
    FOREIGN KEY (`matchs_id`)
    REFERENCES `square_game`.`Matchs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `square_game`.`purchases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `square_game`.`Purchases` (
                                                  `id` INT NOT NULL AUTO_INCREMENT,
                                                  `users_id` INT NOT NULL,
                                                  `date` DATE NULL,
                                                  `product` VARCHAR(45) NULL,
    `price` FLOAT NULL,
    PRIMARY KEY (`id`, `users_id`),
    INDEX `fk_purchases_users1_idx` (`users_id` ASC) VISIBLE,
    CONSTRAINT `fk_purchases_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `square_game`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `square_game`.`packs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `square_game`.`Packs` (
                                              `id` INT NOT NULL,
                                              `name` VARCHAR(45) NULL,
    `n_token` INT NULL,
    `price` FLOAT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `square_game`.`pawns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `square_game`.`Pawns` (
                                              `id` INT NOT NULL AUTO_INCREMENT,
                                              `name` VARCHAR(45) NOT NULL,
    `pattern` VARCHAR(45) NULL,
    `move_rules` JSON NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `square_game`.`games_has_pawns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `square_game`.`games_has_pawns` (
                                                        `games_id` INT NOT NULL,
                                                        `pawns_id` INT NOT NULL,
                                                        PRIMARY KEY (`games_id`, `pawns_id`),
    INDEX `fk_games_has_pawns_pawns1_idx` (`pawns_id` ASC) VISIBLE,
    INDEX `fk_games_has_pawns_games1_idx` (`games_id` ASC) VISIBLE,
    CONSTRAINT `fk_games_has_pawns_games1`
    FOREIGN KEY (`games_id`)
    REFERENCES `square_game`.`Games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_games_has_pawns_pawns1`
    FOREIGN KEY (`pawns_id`)
    REFERENCES `square_game`.`Pawns` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `square_game`.`customizations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `square_game`.`Customizations` (
                                                       `id` INT NOT NULL AUTO_INCREMENT,
                                                       `type` VARCHAR(45) NULL COMMENT 'Type is one of :\npawns set color\npaws set pattern\nboard color',
    `token_cost` INT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `square_game`.`custom_boards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `square_game`.`Custom_boards` (
                                                      `id` INT NOT NULL,
                                                      `users_id` INT NOT NULL,
                                                      `game` INT NOT NULL,
                                                      `color` VARCHAR(45) NULL,
    `is_favorite` TINYINT NULL,
    PRIMARY KEY (`id`, `users_id`),
    INDEX `fk_custom_board_users1_idx` (`users_id` ASC) VISIBLE,
    CONSTRAINT `fk_custom_board_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `square_game`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `square_game`.`custom_pawns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `square_game`.`Custom_pawns` (
                                                     `id` INT NOT NULL,
                                                     `users_id` INT NOT NULL,
                                                     `pawns_id` INT NOT NULL,
                                                     `color` VARCHAR(45) NULL,
    `pattern` VARCHAR(45) NULL,
    `is_favorite` TINYINT NULL,
    PRIMARY KEY (`id`, `users_id`),
    INDEX `fk_custom_pawns_users1_idx` (`users_id` ASC) VISIBLE,
    CONSTRAINT `fk_custom_pawns_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `square_game`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
