-- MySQL Script generated by MySQL Workbench
-- ven. 29 sept. 2023 09:29:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `avatar` VARCHAR(45) NULL,
  `pseudo` VARCHAR(45) NULL,
  `email` VARCHAR(255) NULL,
  `birth_date` DATE NOT NULL,
  `jetons` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `pseudo_UNIQUE` (`pseudo` ASC) VISIBLE,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`games`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`games` ;

CREATE TABLE IF NOT EXISTS `mydb`.`games` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `min_age` INT NULL,
  `size` INT NOT NULL,
  `difficulties` JSON NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`matchs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`matchs` ;

CREATE TABLE IF NOT EXISTS `mydb`.`matchs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `games_id` INT NOT NULL,
  `date_start` DATE NULL,
  `status` VARCHAR(10) NULL,
  `next_player` INT NULL,
  `winner` INT NULL,
  `looser` INT NULL,
  PRIMARY KEY (`id`, `games_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_matchs_games_idx` (`games_id` ASC) VISIBLE,
  CONSTRAINT `fk_matchs_games`
    FOREIGN KEY (`games_id`)
    REFERENCES `mydb`.`games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users_has_matchs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users_has_matchs` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users_has_matchs` (
  `users_id` INT NOT NULL,
  `matchs_id` INT NOT NULL,
  PRIMARY KEY (`users_id`, `matchs_id`),
  INDEX `fk_users_has_matchs_matchs1_idx` (`matchs_id` ASC) VISIBLE,
  INDEX `fk_users_has_matchs_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_matchs_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_matchs_matchs1`
    FOREIGN KEY (`matchs_id`)
    REFERENCES `mydb`.`matchs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`moves`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`moves` ;

CREATE TABLE IF NOT EXISTS `mydb`.`moves` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `matchs_id` INT NOT NULL,
  `pos_start` VARCHAR(45) NULL,
  `pos_end` VARCHAR(45) NULL,
  `date` DATE NULL,
  PRIMARY KEY (`id`, `matchs_id`),
  INDEX `fk_moves_matchs1_idx` (`matchs_id` ASC) VISIBLE,
  CONSTRAINT `fk_moves_matchs1`
    FOREIGN KEY (`matchs_id`)
    REFERENCES `mydb`.`matchs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`purchases`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`purchases` ;

CREATE TABLE IF NOT EXISTS `mydb`.`purchases` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `date` DATE NULL,
  `product` VARCHAR(45) NULL,
  `price` FLOAT NULL,
  PRIMARY KEY (`id`, `users_id`),
  INDEX `fk_purchases_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_purchases_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`packs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`packs` ;

CREATE TABLE IF NOT EXISTS `mydb`.`packs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `n_token` INT NULL,
  `price` FLOAT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pawns`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pawns` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pawns` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `pattern` VARCHAR(45) NULL,
  `move_rules` JSON NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`games_has_pawns`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`games_has_pawns` ;

CREATE TABLE IF NOT EXISTS `mydb`.`games_has_pawns` (
  `games_id` INT NOT NULL,
  `pawns_id` INT NOT NULL,
  PRIMARY KEY (`games_id`, `pawns_id`),
  INDEX `fk_games_has_pawns_pawns1_idx` (`pawns_id` ASC) VISIBLE,
  INDEX `fk_games_has_pawns_games1_idx` (`games_id` ASC) VISIBLE,
  CONSTRAINT `fk_games_has_pawns_games1`
    FOREIGN KEY (`games_id`)
    REFERENCES `mydb`.`games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_games_has_pawns_pawns1`
    FOREIGN KEY (`pawns_id`)
    REFERENCES `mydb`.`pawns` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customizations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`customizations` ;

CREATE TABLE IF NOT EXISTS `mydb`.`customizations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL COMMENT 'Type is one of :\npawns set color\npaws set pattern\nboard color',
  `token_cost` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `type_UNIQUE` (`type` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`custom_boards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`custom_boards` ;

CREATE TABLE IF NOT EXISTS `mydb`.`custom_boards` (
  `id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `game` INT NOT NULL,
  `color` VARCHAR(45) NULL,
  `is_favorite` TINYINT NULL,
  PRIMARY KEY (`id`, `users_id`),
  INDEX `fk_custom_board_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_custom_board_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`custom_pawns`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`custom_pawns` ;

CREATE TABLE IF NOT EXISTS `mydb`.`custom_pawns` (
  `id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `pawns_id` INT NOT NULL,
  `color` VARCHAR(45) NULL,
  `pattern` VARCHAR(45) NULL,
  `is_favorite` TINYINT NULL,
  PRIMARY KEY (`id`, `users_id`),
  INDEX `fk_custom_pawns_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_custom_pawns_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users_has_customizations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users_has_customizations` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users_has_customizations` (
  `users_id` INT NOT NULL,
  `customizations_id` INT NOT NULL,
  PRIMARY KEY (`users_id`, `customizations_id`),
  INDEX `fk_users_has_customizations_customizations1_idx` (`customizations_id` ASC) VISIBLE,
  INDEX `fk_users_has_customizations_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_customizations_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_customizations_customizations1`
    FOREIGN KEY (`customizations_id`)
    REFERENCES `mydb`.`customizations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
